### ISSUE TITLE
Switch execute commands to second terminal

### ISSUE THREAD

**Issue by theckang** [RedHatGov/serverless-workshop-dashboard#28]
In some cases, the bash commands should be executed in a second terminal in homeroom.  We should annotate like so

\```execute-2
$ bash command
\```

**Comment by jkeam** [comment]
The supported lexers that Github uses are here: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml 

`execute` and `execute-2` are not on that list, meaning it won't get syntax highlighting.  But this markdown will be displayed within the context of Homeroom, which I'm assuming uses the same lexer as Github.

Thoughts?

**Comment by theckang** [comment]
It looks like this 
<img width="1355" alt="Screen Shot 2021-04-15 at 11 24 07 AM" src="https://user-images.githubusercontent.com/10468378/114904196-37892480-9ddd-11eb-9c27-20ba07bbbfdc.png">

If you add `execute`, you get a "arrow button" that you can click and it will execute the command in the window for you.  `execute-2` will execute that command in the second (bottom) window.

If your concern is "code highlighting", I don't think homeroom will respect it anyway.  For example, this command block below uses bash but it doesn't highlight anyway.  And you don't get the arrow button.  So the user will have to copy and paste manually.

<img width="1362" alt="Screen Shot 2021-04-15 at 11 24 29 AM" src="https://user-images.githubusercontent.com/10468378/114905372-808da880-9dde-11eb-8ef5-5e4c04e8d1f6.png">

**Comment by theckang** [comment]
*edit* oops: The curl commands are a bad example.  check out the other image I uploaded above.

To be explicit, I don't think supported lexers matter because there's no highlighting.  In addition, you can't get the arrow buttons unless you explicitly use `execute` or `execute-2`.  This is most likely homeroom specific functionality.

**Comment by jkeam** [comment]
Ah ok that makes sense.  I should go back and change all the `shell` to `execute` as well.  I wasn't aware of the homeroom specific thing.

**Comment by theckang** [comment]
Homeroom magic :)

**Comment by jkeam** [comment]
Going to mark this resolved by PR https://github.com/RedHatGov/serverless-workshop-dashboard/pull/29
