### ISSUE TITLE
Pin workshop to specific version of Serverless

### ISSUE THREAD

**Issue by jkeam** [RedHatGov/serverless-workshop-dashboard#3]
In the future, we will need to pin our workshop to a specific version of Serverless. So, we'll have to use the ClusterServiceVersion API. I actually think we should do this now.

**Comment by jkeam** [comment]
@theckang I remember you mentioning that you tried something with the ServiceMesh workshop and it didn't work as expected.  Wondering if you could lend some guidance from things you learned from that experience here.

**Comment by theckang** [comment]
Yes, so I tried pinning the operator versions like this for service mesh: https://github.com/RedHatGov/sre-workshop-code/blob/9dca07e766996b481ef5baea6a93ff503f71c7fb/setup/istio-operators.yaml

It worked for awhile, but then it stopped working so I ended up giving up.  I think the `startingCSVs` change so it's hard to make this reliable.

Honestly, I can't find a good solution to this so I'd be ok if we closed it and moved forward with Channels.  Not perfect, but let's not spend too much time if it's too difficult.

**Comment by dudash** [comment]
https://github.com/redhat-cop/agnosticd/blob/development/docs/Operator_Catalog_Snapshots.adoc

**Comment by jkeam** [comment]
Awesome good link @dudash .  Gonna mark this is a low priority/nice to have at this point while we work to finalize some of the other details around this.

**Comment by theckang** [comment]
agnosticD role pins the OpenShift Serverless version now.
