### ISSUE TITLE
Deploy User Assignment App as part of the user name distribution

### ISSUE THREAD

**Issue by gbengataylor** [RedHatGov/serverless-workshop-dashboard#38]
use https://github.com/RedHatGov/username-distribution

or https://github.com/RedHat-Middleware-Workshops/username-distribution

**Comment by jkeam** [comment]
I think this setup should live in the serverless-workshop-code repo.  So I'm going to close this issue in favor of using this ticket I just opened https://github.com/RedHatGov/serverless-workshop-code/issues/15
