### ISSUE TITLE
Lab 1.1 What is a serverless could be broken up a bit

### ISSUE THREAD

**Issue by andykrohg** [RedHatGov/serverless-workshop-dashboard#40]
> This project provides a vendor agnostic way of making containers serverless capable. It does this by applying two key concepts, serving and eventing to be able to create dynamically scaling, loosely coupled event driven applications.

We could do better justice to Serving and eventing here by breaking out of prose and doing something like:

It does this by applying two key concepts:
* **Serving** - [ high level definition of serving]
* **Eventing** - [ high level definition of eventing]

**Comment by jkeam** [comment]
PR https://github.com/RedHatGov/serverless-workshop-dashboard/pull/60

**Comment by jkeam** [comment]
PR Merged
