### ISSUE TITLE
Lab 1.3 Tools section - use %cluster_subdomain% to template the URL in

### ISSUE THREAD

**Issue by andykrohg** [RedHatGov/serverless-workshop-dashboard#42]
for example https://console-openshift-console.%cluster_subdomain%/command-line-tools

This functionality is provided by workshop-dashboard

**Comment by gbengataylor** [comment]
And change the text to 


The environment set up for you to perform this lab should have all the tools pre-installed already. The oc and kn tools are available on  OpenShift at https://console-openshift-console.%cluster_subdomain%/command-line-tools.

**Comment by jkeam** [comment]
PR https://github.com/RedHatGov/serverless-workshop-dashboard/pull/61

**Comment by jkeam** [comment]
PR Merged
