### ISSUE TITLE
Lab 1.5 duplicate "set user number" instruction typo

### ISSUE THREAD

**Issue by thadd** [RedHatGov/serverless-workshop-dashboard#43]
In the Set Topic section of Lab 1.5 the instruction to set user number is duplicated in a copy-paste error.

**Comment by andykrohg** [comment]
Rather than bothering with setting a #USER_NUMBER shell variable, you can just interpolate `%username%` into the lab markdown directly.

**Comment by jkeam** [comment]
Fixed by your PR and @TheRealCabrera https://github.com/RedHatGov/serverless-workshop-dashboard/pull/48
