### ISSUE TITLE
Lab 1.4 Deploy service looks weird with numbered task in lays

### ISSUE THREAD

**Issue by andykrohg** [RedHatGov/serverless-workshop-dashboard#45]
![image](https://user-images.githubusercontent.com/5431427/117054870-8e04c700-ace8-11eb-842f-4168c144e7ed.png)

Might be better instead of using numbers for these:
1. Use your project
2. Build the project
...

To use section headers instead, like
### Build the project

**Comment by jkeam** [comment]
PR https://github.com/RedHatGov/serverless-workshop-dashboard/pull/62

**Comment by jkeam** [comment]
PR Merged
