### ISSUE TITLE
Comments in runnable commands get sent over to terminal

### ISSUE THREAD

**Issue by TheRealCabrera** [RedHatGov/serverless-workshop-dashboard#51]
Lab 1.5 
Create Topic:
 - verify it was created
  - ```# a nice shortcut is 'oc get kt'```

See it in action:
 - ```#it's ok to get "error: the server doesn't have a resource type "kafka-producer""```
  - Additionally the error I got was actually "Error from server (NotFound): pods "kafka-producer" not found"

**Comment by jkeam** [comment]
PR https://github.com/RedHatGov/serverless-workshop-dashboard/pull/63

**Comment by jkeam** [comment]
PR Merged
