### ISSUE TITLE
Lab1.4 Fix the 'Deploy the updated service'

### ISSUE THREAD

**Issue by theckang** [RedHatGov/serverless-workshop-dashboard#52]
1. `kn service update` does not need the image
2. Break out the 'create' alternative
3. '-f' is not force

In some cases, the user didn't see the `Pythonistas` even when the service was updated.  It required force create to fix the issue.

**Comment by jkeam** [comment]
`--force`
https://github.com/knative/client/blob/c62842355a532a4c69dccdb2cc6dc1b5f1d0f937/pkg/kn/commands/service/create.go

**Comment by jkeam** [comment]
Maybe we should just change the `update` to `create`?

**Comment by jkeam** [comment]
PR https://github.com/RedHatGov/serverless-workshop-dashboard/pull/62

**Comment by jkeam** [comment]
PR Merged
